config/routes.rb
Rails.application.routes.draw do
  resources :timesheets, path: '/', only: %i[index new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timesheet.rb
# == Schema Information
#
# Table name: timesheets
#
#  id          :bigint           not null, primary key
#  amount      :float            default(0.0)
#  date        :date             not null
#  finish_time :integer          default(0), not null
#  start_time  :integer          default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Timesheet < ApplicationRecord
  validates :date, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
  validates :finish_time, numericality: { greater_than_or_equal_to: :start_time, message: ' can\'t before start time.' }, unless: -> { start_time.nil? }

  validate :date_cannot_be_in_the_future, :entry_cannot_overlap

  before_save :calculate_amount

  def show_data(with_money: true)
    "#{date.strftime('%d/%m/%Y')}: #{start_time_string} - #{finish_time_string}" + (with_money ? " $#{amount}" : '')
  end

  def start_time_string
    TimeService.seconds_to_hm(start_time)
  end

  def finish_time_string
    TimeService.seconds_to_hm(finish_time)
  end

  def calculate_amount
    assign_attributes amount: AmountService.new(self).calculate_amount
  end

  private

  def date_cannot_be_in_the_future
    errors.add(:date, 'can\'t be in the future') if date.present? && date > Date.today
  end

  def entry_cannot_overlap
    others = Timesheet.where(date: date)
    others.each do |other|
      if start_time <= other.finish_time && other.start_time <= finish_time
        errors.add(:base, "Current entry is overlapping with #{other.show_data(with_money: false)}.")
        break
      end
    end
  end
end

app/models/weekday_rate.rb
# == Schema Information
#
# Table name: weekday_rates
#
#  id          :bigint           not null, primary key
#  day_of_week :integer          not null
#  end_time    :integer          default(0), not null
#  rate        :float            default(0.0), not null
#  start_time  :integer          default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class WeekdayRate < ApplicationRecord
  validate :weekrate_cannot_overlap
  enum day_of_week: { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }

  private

  def weekrate_cannot_overlap
    others = WeekdayRate.where(day_of_week: day_of_week)
    others.each do |other|
      if start_time <= other.end_time && other.start_time <= end_time
        errors.add(:base, 'Weekday rate is overlapping.')
        break
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: %i[show edit update destroy]

  # GET /timesheets or /timesheets.json
  def index
    @timesheets = Timesheet.all
  end

  # GET /timesheets/1 or /timesheets/1.json
  def show; end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit; end

  # POST /timesheets or /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)
    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to timesheets_url, notice: 'New timesheet was successfully created.' }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1 or /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to timesheet_url(@timesheet), notice: 'Timesheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1 or /timesheets/1.json
  def destroy
    @timesheet.destroy

    respond_to do |format|
      format.html { redirect_to timesheets_url, notice: 'Timesheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_timesheet
    @timesheet = Timesheet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def timesheet_params
    fetch_params = params.fetch(:timesheet, {}).permit(:date, :start_hour, :start_minutes, :finish_hour, :finish_minutes)
    fetch_params[:start_time] = time_to_seconds fetch_params.delete(:start_hour), fetch_params.delete(:start_minutes)
    fetch_params[:finish_time] = time_to_seconds fetch_params.delete(:finish_hour), fetch_params.delete(:finish_minutes)

    fetch_params
  end

  def time_to_seconds(hour, minute)
    return unless hour.present? && minute.present?

    "#{hour}:#{minute}".to_time.seconds_since_midnight
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTimesheet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timesheets/_form.html.erb
<%= form_with(model: timesheet) do |form| %>
  <% if timesheet.errors.any? %>
    <div id="error_explanation">
      <h2>Oh no there's something wrong :(</h2>

      <ul>
        <% timesheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= form.label :date %>
    <%= form.date_field :date, max: Date.today %>
  </div>
  <div class='field'>
    <%= form.label :start_time %>
    <%= form.number_field :start_hour, in: 0..23, value: 8 %>
    <span>:</span>
    <%= form.number_field :start_minutes, in: 0..59, value: 0 %>
  </div>
  <div class='field'>
    <%= form.label :finish_time %>
    <%= form.number_field :finish_hour, in: 0..23, value: 17 %>
    <span>:</span>
    <%= form.number_field :finish_minutes, in: 0..59, value: 0 %>
  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing Timesheet</h1>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'Create Timesheet Entry', new_timesheet_path, method: 'get' %>

<h2>Timesheets Entries</h2>

<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= timesheet.show_data %></td>
        <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/timesheets/new.html.erb
<h2>Create Timesheet Entry</h2>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>